server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: "configserver:http://localhost:8888"

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/order/**

        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/inventory/**

  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
